//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOgrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOgrenci()
        {
            this.TblNot = new HashSet<TblNot>();
        }
    
        public int Ogrid { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string OgrFoto { get; set; }
        public string OgrCinsiyet { get; set; }
        public Nullable<byte> OgrKulup { get; set; }
    
        public virtual TblKulup TblKulup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblNot> TblNot { get; set; }
    }
}
